#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE_SOURCE_TYPE="$2"; TMP_WORK_DIR="$3"; REV="$4"

echo "Pre receive app NPM-CACHE"

if [[ -f "$DOKKU_ROOT/NPM-CACHE" ]]; then
	if [[ "$IMAGE_SOURCE_TYPE" == "dockerfile"]]; then
  		echo "-----> Parsing Dockefile ..."
  		cat Dockerfile
  	fi
fi
